django5/app5/urls.py
from django.urls import path , re_path , include
from app5 import views


app_name = 'app5'

urlpatterns = [

re_path(r'^register/$',views.register,name='register'),
re_path(r'^user_login/$',views.user_login,name='user_login')

]

django5/django5/urls.py
from django.contrib import admin
from django.urls import path , re_path , include
from app5 import views
urlpatterns = [
    re_path(r'^$', views.index , name = 'index'),
    re_path(r'^app5/',include('app5.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^logout',views.user_logout,name='logout')
]

django5/app5/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

django5/app5/forms.py
from django import forms
from django.contrib.auth.models import User
from app5.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

django5/app5/views.py
from django.shortcuts import render

# Create your views here.
from app5.forms import UserProfileInfoForm , UserForm




# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required




def index(request):
    return render(request,'/home/ajink7/django3/django5/templates/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'/home/ajink7/django3/django5/templates/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})




def user_login(request):

    if request.method=='POST' :
        un = request.POST.get("username")
        ps = request.POST.get("password")

        user1 = authenticate(username=un,password = ps)

        if user1:

            if user1.is_active :
                login(request,user1)
                return HttpResponseRedirect(reverse('index'))

            else :
                HttpResponse('Account not active')

        else:
            return HttpResponse("Invalid password and id")


    else:
        return render(request,'/home/ajink7/django3/django5/templates/login.html')

django5/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'app5:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li> <a class = "navbar-link" href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class="navbar-link" href="{% url 'app5:user_login' %}">Login</a> </li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>



</html>

django5/templates/index.html
{% extends "/home/ajink7/django3/django5/templates/base.html" %}

{% block body_block %}
  <div class="jumbotron">
    {% if user.is_authenticated %}
    <h1>Welcome to django </h1>
    <h1>{{ user.username }}</h1>
    {% else %}
    <h1>Welcome to django</h1>
    {% endif %}
  </div>

{% endblock %}

django5/templates/login.html
{% extends '/home/ajink7/django3/django5/templates/base.html' %}
{% block body_block %}
<div class="jumbotron">

  <form  method="post" action="{% url 'app5:user_login' %}" >
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" value="">
    <label for="password">Password</label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

django5/templates/registration.html
{% extends "/home/ajink7/django3/django5/templates/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}